'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default
    
    '''<summary>
    '''LogonPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogonPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''VibeLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VibeLogo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''LogonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogonID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LogonPIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogonPIN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''MainPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''MainScreenUsernamelabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainScreenUsernamelabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UMSNBCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UMSNBCheck As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''UMSNBHyperlink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UMSNBHyperlink As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''GBANKCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GBANKCheck As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''GBANKHyperlink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GBANKHyperlink As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''RIVERCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RIVERCheck As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RIVERHyperlink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RIVERHyperlink As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''UMSBLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UMSBLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GBANKBLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GBANKBLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RIVERBLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RIVERBLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TotalBLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalBLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LogoutButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogoutButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TransferButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransferButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SendButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SendButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RefreshButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefreshButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BankQuestionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankQuestionPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''BQBankLBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BQBankLBL As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BQYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BQYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BQNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BQNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DirectoryPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectoryPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ListBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBox1 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''DirectoryOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectoryOK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DirectoryCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DirectoryCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SendMoneyPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SendMoneyPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''SendFromLBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SendFromLBL As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UMSNBRButtonSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UMSNBRButtonSend As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''GBANKRButtonSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GBANKRButtonSend As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RIVERRButtonSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RIVERRButtonSend As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''SendToLBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SendToLBL As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UMSNBRButtonSendTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UMSNBRButtonSendTo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''GBANKRButtonSendTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GBANKRButtonSendTo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RIVERRButtonSendTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RIVERRButtonSendTo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''SendAmountTXB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SendAmountTXB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SendMoneyOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SendMoneyOK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SendMoneyCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SendMoneyCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TransferPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransferPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UMSNBRButtonTFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UMSNBRButtonTFrom As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''GBANKRButtonTFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GBANKRButtonTFrom As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RIVERRButtonTFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RIVERRButtonTFrom As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''UMSNBRButtonTTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UMSNBRButtonTTo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''GBANKRButtonTTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GBANKRButtonTTo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RIVERRButtonTTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RIVERRButtonTTo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''TransferAmountTXB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransferAmountTXB As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TransferMoneyOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransferMoneyOK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TransferMoneyCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransferMoneyCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BankWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankWindow As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''BankLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankLogo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''BankLogTextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BankLogTextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CloseBABTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CloseBABTN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LogOKButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogOKButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''NotifPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotifPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''NotifLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotifLabel As Global.System.Web.UI.WebControls.Label
End Class
